services:
  # A Docker web service
  - type: web
    name: Chevereto
    env: docker
    repo: https://github.com/AkashiCoin/Chevereto-railway.git # optional
    region: Singapore  # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
      
